using System.Windows;

namespace Epxoxy.Controls
{
    public class DataGridHelper
    {
        public static bool GetAutoGeneratedId(DependencyObject obj)
        {
            return (bool)obj.GetValue(AutoGeneratedIdProperty);
        }
        public static void SetAutoGeneratedId(DependencyObject obj, bool value)
        {
            obj.SetValue(AutoGeneratedIdProperty, value);
        }

        public static readonly DependencyProperty AutoGeneratedIdProperty =
            DependencyProperty.RegisterAttached("AutoGeneratedId", typeof(bool), typeof(DataGridHelper),
                new PropertyMetadata(false, OnAutoGeneratedIdChanged));

        private static void OnAutoGeneratedIdChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var datagrid = d as System.Windows.Controls.DataGrid;
            if (datagrid != null)
            {
                if ((bool)e.NewValue)
                {
                    datagrid.LoadingRow -= OnDatagridLoadingRow;
                    datagrid.LoadingRow += OnDatagridLoadingRow;
                }
                else
                {
                    datagrid.LoadingRow -= OnDatagridLoadingRow;
                }
            }
        }

        private static void OnDatagridLoadingRow(object sender, System.Windows.Controls.DataGridRowEventArgs e)
        {
            e.Row.Header = e.Row.GetIndex() + 1;
        }
    }
}